### ISSUE TITLE
Auto loot confused by items with comma in the name

### ISSUE THREAD

**Issue by martinlindhe** [cream24/Macros#6]
Consider this item "Bloodstained Journal, Vol 2"

Written to INI it becomes:
"Bloodstained Journal=Keep"

http://everquest.allakhazam.com/db/item.html?item=48698

**Comment by martinlindhe** [comment]
I must add that the current code worked well for me across loads of zones. Its just cazic thule with these common drop bloodstained journals that messes things up. Can live with no changes if it complicates things too much.
I realize the comma is used as a separator in the WriteToIni function

**Comment by wmrojer** [comment]
Have had the same problem in Katta. Items with , was not getting looted by my bots since the item name was written incorrectly to the ini file. I have rewritten the code so it at least works for items with , even thou they get written wrongly to the ini.

I tried /if (${itemName.Find[,]}) /varset itemName ${itemName.Replace[",",.]} to replace the , with . as is already done with : to ; but that seems to crash MQ2 every time.

**Comment by cream24** [comment]
this one was a pita but have it sorted, replacing a comma does in fact crash eq - macroquest bug
